### PR TITLE
Adding Benjamin B Thompson to the Author List

### PR DESCRIPTION
**Pull request by cosmosquark**
It has been a while since I have contributed to this, but during my PhD days I contributed towards
- relative particles positions and velcoities
- RAMSES related code.

I might have some time to take a glance over the paper once it is done.

I have learned a lot from working on this project back in the day, and would recommend anyone who is interested in learning about open source software to take a look at this project.

### CODE REVIEW

**Comment by matthewturk** [comment]
Hi @cosmosquark , you also filled out the google form, right?

**Comment by matthewturk** [comment]
@cosmosquark Can you take a look at how you're listed at https://yt-project.github.io/yt-4.0-paper/ (as a result of #121 ) and see if it looks OK?

**Comment by cosmosquark** [comment]
> @cosmosquark Can you take a look at how you're listed at https://yt-project.github.io/yt-4.0-paper/ (as a result of #121 ) and see if it looks OK?

Hello.

Yes, I did fill out the google form. 

Looks good in that build, however for affiliations I would like to include

      - Jeremiah Horrocks Institute, University of Central Lancashire, Preston, Lancashire, PR1 2HE, UK
      - Institute for Computational Astrophysics, Dept of Astronomy & Physics, Saint Mary’s University, Halifax, BH3 3C3, Canada

And for funding
      - STFC PhD Studentship programme (ST/F007701/1)

Which isn't included in the current draft.

How do I add these details to the current draft?

**Comment by matthewturk** [comment]
I actually did not mean to close the PR!  That was a mistake.  I'll reopen with this comment.

**Comment by matthewturk** [comment]
We'll merge, then remove the other inclusion.

**Pull request merged**
