### PR TITLE
Adding John Wise to author list

### PR DESCRIPTION
**Pull request by jwise77**
I haven't contributed to yt in several years because of added admin duties. I authored the `eps_writer` submodule that needs to be extracted into its own package (yt-project/yt#3498). I can do this in May after classes end and write a paragraph about it in _Ecosystem of Packages_, if desired.

### CODE REVIEW

**Comment by jwise77** [comment]
It looks like it failing, but it should pass after #124 is merged.

**Comment by matthewturk** [comment]
Your contributions are sufficient without that change, @jwise77 !  Thank you.

**Comment by matthewturk** [comment]
I'm going to merge and then go back and fix the warnings manubot found.

**Comment by jwise77** [comment]
Sounds good and you're welcome!

**Pull request merged**
